### ISSUE TITLE
Make getKeyValueMap exported

### ISSUE THREAD

**Issue by cn007b** [PaddleHQ/go-aws-ssm#19]
Could you please make method [getKeyValueMap](https://github.com/PaddleHQ/go-aws-ssm/blob/master/parameter.go#L73) exported (GetKeyValueMap)?

**Comment by geototti21** [comment]
👋 Hey @cn007b, sounds good. 
We can add a `GetAllValues() map[string]string` method that will return the result of this.
PRs are more than welcome 😄 🚀

**Comment by cn007b** [comment]
https://github.com/PaddleHQ/go-aws-ssm/pull/21
