### ISSUE TITLE
Issue with copy in method Read.

### ISSUE THREAD

**Issue by cn007b** [PaddleHQ/go-aws-ssm#20]
Got issue [here](https://github.com/PaddleHQ/go-aws-ssm/blob/master/parameter.go#L44) because in my case `bytesJSON` has 790 bytes but [viper](https://github.com/spf13/viper/blob/master/viper.go#L1391) uses default `bytes.Buffer` with `MinRead = 512` and `io.EOF` on line 44 means that my JSON will be corrupted. So looks like `Read` must be implemented in better way...

**Comment by geototti21** [comment]
fixed by #23
