### ISSUE TITLE
Trying to read parameter store value greater than 512 bytes into viper returns 'While parsing config: unexpected end of JSON input` error

### ISSUE THREAD

**Issue by mjevans93308** [PaddleHQ/go-aws-ssm#26]
Hi,

I'm storing a relatively large value in AWS Param Store that is greater than 512 bytes. What I'm seeing is that when I try to fetch that value from Param Store, it gets the full value, but when I try to feed that value into viper using `viper.ReadConfig(params)` it only feeds the first 512 bytes of the param value.

Code:
```
params, err = ssm.GetAllParametersByPath(ssmPath, true)
if err != nil {
    return
}

// inspecting the individual params here shows that the full value has been captured

err = viper.ReadConfig(params)
// err returned: While parsing config: unexpected end of JSON input
```

I've pinpointed where the error is coming from:
In `buffer.go`, the minimum size of the buffer initialized in `buffer.ReadFrom(r io.Reader)` is 512 bytes. It is suppose to automatically increase the size of the buffer when it gets to that predefined size and doesn't find an EOF char during `r.Read(...)`:
```// MinRead is the minimum slice size passed to a Read call by
// Buffer.ReadFrom. As long as the Buffer has at least MinRead bytes beyond
// what is required to hold the contents of r, ReadFrom will not grow the
// underlying buffer.
const MinRead = 512

// ReadFrom reads data from r until EOF and appends it to the buffer, growing
// the buffer as needed. The return value n is the number of bytes read. Any
// error except io.EOF encountered during the read is also returned. If the
// buffer becomes too large, ReadFrom will panic with ErrTooLarge.
func (b *Buffer) ReadFrom(r io.Reader) (n int64, err error) {
	b.lastRead = opInvalid
	for {
		i := b.grow(MinRead)
		b.buf = b.buf[:i]
		m, e := r.Read(b.buf[i:cap(b.buf)])
		if m < 0 {
			panic(errNegativeRead)
		}

		b.buf = b.buf[:i+m]
		n += int64(m)
		if e == io.EOF {
			return n, nil // e is EOF, so return nil explicitly
		}
		if e != nil {
			return n, e
		}
	}
}
```
`parameter.go` implements the `io.Reader`'s `Read` like so:
```//Read implements the io.Reader interface for the key/value pair
func (p *Parameters) Read(des []byte) (n int, err error) {
	bytesJSON, err := json.Marshal(p.getKeyValueMap())
	if err != nil {
		return 0, err
	}
	return copy(des, bytesJSON), io.EOF
}
```

This means that we are returning an `io.EOF` regardless of if we've read the full param value.

So we return the first 512 bytes back to `buffer.ReadFrom(...)` along with the io.EOF, which `buffer.ReadFrom(..)` interprets as being finished with the full message, so it doesn't try to enlarge the buffer and read more of the value, thus chopping off the end of the value (including the end JSON `}`), which is why we end up with the `unexpected end of JSON content` error.

The limit on the value as described by AWS for Param Store entries is 8Kb for advanced keys or 4Kb for normal keys, so I felt I should bring this issue to the repo's owners attention.

Hope you are having a good day!

**Comment by geototti21** [comment]
👋 hey @mjevans93308, this issue was resolved on #23 . so please update on the [v0.5.0 version](https://github.com/PaddleHQ/go-aws-ssm/releases/tag/v0.5.0)
