### ISSUE TITLE
New session with options

### ISSUE THREAD

**Issue by icy95** [PaddleHQ/go-aws-ssm#33]
Hi, i tried the basic usage, but it does not get the default region unfortunately. So, i added the region as;

`pmstore, err := awsssm.NewParameterStore(aws.NewConfig().WithRegion("eu-west-1"))`

Like this, it works. But i don't want to pass region in code. And way to do it, we need create NewSessionWithOptions and enable the SharedConfig, as;

 func NewParameterStore(ssmConfig ...*aws.Config) (*ParameterStore, error) {

	sessionAWS, err := session.NewSessionWithOptions(session.Options{
		SharedConfigState: session.SharedConfigEnable,
	})
	if err != nil {
		return nil, err
	}
	svc := ssm.New(sessionAWS)
	return &ParameterStore{ssm: svc}, nil 
 }

Is there any way to do it without manipulating this function ?

**Comment by sebastian-mora** [comment]
I was able to do it this way 

```
sess := session.Must(session.NewSessionWithOptions(session.Options{
SharedConfigState: session.SharedConfigEnable,
}))

pmstore, err := awsssm.NewParameterStore(sess.Config)
```
